name: data-science-from-scratch-haskell
version: '0.0.0'
category: template
synopsis: Data Science from Scratch, the Haskell Way
description: >
  aims to reproduce all code examples from Data Science from Scratch using Haskell
author: Thomas Peiselt
github: dispanser/data-science-from-scratch-haskell
license: MIT

ghc-options: -Wall
dependencies:
  - base >= 4.8.0 && <5

library:
  source-dirs: src
  dependencies:
    - containers
    - unordered-containers
    - hashable
    - microlens
    - Chart

tests:
  eval:
    source-dirs: eval
    main: Eval/Libs.hs
    dependencies:
      - data-science-from-scratch-haskell
      - chart-unit
      - microlens
      - generic-lens
      - numhask-prelude
  tasty:
    source-dirs: tasty
    main: TastyTests.hs
    dependencies:
      - containers
      - unordered-containers
      - data-science-from-scratch-haskell
      - hspec
      - QuickCheck
      - tasty
      - tasty-quickcheck
      - tasty-hunit
      - tasty-hspec

benchmarks:
  benchmark-criterion:
    main: Bench.hs
    source-dirs: bench
    ghc-options:
      - -threaded
    dependencies:
      - data-science-from-scratch-haskell
      - criterion
