resolver: lts-12.14
packages:
  - '.'
extra-deps:
  - diagrams-lib-1.4.2.3
  - diagrams-svg-1.4.2
  - test-invariant-0.4.5.0
  - Chart-1.9
  # - generic-lens-labels-0.1.0.2
  # - base-4.10.1.0
  # - generic-lens-0.5.1.0

allow-newer: true

nix:
  enable: true
  packages: []
